Algoritmo "L03B"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar o total da soma obtida dos cem primeiros números inteiros
// Autor(a)    : Natailson Gois
// Data atual  : 01/10/2025
Var
// Seção de Declarações das variáveis 
contador, soma : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 1 ate 100 faca
soma <- soma + contador
escreval (soma)
fimpara

Fimalgoritmo